{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Parameter1\",\"Transform Sample File\",\"Sample File\",\"Transform File\",\"Weekday sort\",\"Pivotted\",\"Raw data\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.122.746.0 (23.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Parameter1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "fc0fb5e8-10d5-4402-b273-a8d37b8cbe8e",
        "queryGroup": "Transform File from Records\\Helper Queries"
      },
      {
        "name": "Transform Sample File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(Parameter1, null, true),",
          "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "e3bf47cc-a252-41e0-9bba-cdc081e91cca",
        "queryGroup": "Transform File from Records"
      },
      {
        "name": "Sample File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(\"C:\\Users\\JackMacCormick\\OneDrive - Diabetes Australia\\Documents\\_Times\\Records\"),",
          "    Navigation1 = Source{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "bf43b2aa-2b84-494c-9895-5f617f0c7361",
        "queryGroup": "Transform File from Records\\Helper Queries"
      },
      {
        "name": "Transform File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter1 as binary) => let",
          "    Source = Excel.Workbook(Parameter1, null, true),",
          "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "bda78f9e-0c9a-456c-81c3-11ba94f0f766",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File\"\"}\" ]",
        "queryGroup": "Transform File from Records\\Helper Queries"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Records"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Records\\Helper Queries"
      }
    ],
    "relationships": [
      {
        "name": "42796f81-7da4-434b-af09-0ed61c9c344b",
        "fromColumn": "Week Start",
        "fromTable": "Pivotted",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b1b8f686-946b-4700-b7d7-a0032341467f"
      },
      {
        "name": "d4716a41-a594-4a2f-be71-016a65481e03",
        "fromColumn": "Day",
        "fromTable": "Pivotted",
        "toColumn": "Day",
        "toTable": "Weekday sort"
      }
    ],
    "sourceQueryCulture": "en-AU",
    "tables": [
      {
        "name": "Raw data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Source.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6164bb2e-45f6-486f-90a6-fe1d3d591317",
            "sourceColumn": "Source.Name",
            "summarizeBy": "none"
          },
          {
            "name": "Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20635343-f8f4-4c52-a0d7-815204877f4a",
            "sourceColumn": "Time",
            "summarizeBy": "none"
          },
          {
            "name": "Monday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d87fb900-dd64-458d-b1ac-b3f734d37d6f",
            "sourceColumn": "Monday",
            "summarizeBy": "none"
          },
          {
            "name": "Tuesday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a083395-211f-4c87-abb6-d90c27f2f173",
            "sourceColumn": "Tuesday",
            "summarizeBy": "none"
          },
          {
            "name": "Wednesday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0fe0e0f9-59f2-4322-ad32-8a51b432fcc4",
            "sourceColumn": "Wednesday",
            "summarizeBy": "none"
          },
          {
            "name": "Thursday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfce7b2e-b8c9-4204-9652-11ab2ea83f21",
            "sourceColumn": "Thursday",
            "summarizeBy": "none"
          },
          {
            "name": "Friday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "468ef574-ec33-4d2a-b17a-d14b13dcd3a5",
            "sourceColumn": "Friday",
            "summarizeBy": "none"
          },
          {
            "name": "Saturday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd92558d-c49c-4c5e-b336-38898690b98f",
            "sourceColumn": "Saturday",
            "summarizeBy": "none"
          },
          {
            "name": "Sunday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea95d352-0c91-4c56-b8fb-b95f2169c488",
            "sourceColumn": "Sunday",
            "summarizeBy": "none"
          },
          {
            "name": "Notes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "caba999d-316d-45c5-85d4-0285f1912a47",
            "sourceColumn": "Notes",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "43ef1250-1f83-4431-92c6-94c08ac36687",
        "partitions": [
          {
            "name": "Raw data-70b164ce-2476-4fa9-9e67-35efb3f79966",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"C:\\Users\\JackMacCormick\\OneDrive - Diabetes Australia\\Documents\\_Times\\Records\"),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File\", each #\"Transform File\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File\", Table.ColumnNames(#\"Transform File\"(#\"Sample File\")))",
                "in",
                "    #\"Expanded Table Column1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_093cc6d0-ac98-4d86-b242-8f6c76159c97",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "32bb1e59-0551-4f8d-9243-59e5160d7169",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1b324918-5c71-499c-9624-e522d3ca83ec",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "789ef2ab-2a01-4673-8093-dc65f4027cef",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "83d704cf-4dbc-4145-b05a-1e0066717252",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6569016f-c4b7-46fd-a6af-3926a8e20a23",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "21acfc26-4a04-4f74-812f-4e5b8ce90baf",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5970f66a-cd6f-48fc-9b70-04c91ba8c980",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "325b9ad7-5916-4507-8ae8-17ef20ba6341",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "595c966f-06cd-4766-9bb7-2a4b3eba4bf9",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6005ecad-8097-4eee-a325-8970a6d8a483",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "9bd8a532-aa94-4962-b86d-7d2b1948249c",
                "ordinal": 3
              }
            ],
            "lineageTag": "9418012b-c42b-453a-a85d-ebab35989aed"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "4025f6f1-9e54-43cd-b295-c38ca168d22b",
        "partitions": [
          {
            "name": "DateTableTemplate_093cc6d0-ac98-4d86-b242-8f6c76159c97-50ac2dff-ef86-4868-b97b-5722276bdb3d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Pivotted",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Week Start",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c4410ce3-f6a3-4b88-b5ea-2afa2912bf05",
            "sourceColumn": "Week Start",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_b1b8f686-946b-4700-b7d7-a0032341467f"
                },
                "isDefault": true,
                "relationship": "42796f81-7da4-434b-af09-0ed61c9c344b"
              }
            ]
          },
          {
            "name": "Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "hh:nn",
            "lineageTag": "29beaaa9-4f7f-430a-bcac-05e615261e7e",
            "sourceColumn": "Time",
            "summarizeBy": "none"
          },
          {
            "name": "Week Start - Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5e4de2b-aad5-4a29-8fd7-7b6b374a2580",
            "sourceColumn": "Week Start - Sort",
            "summarizeBy": "none"
          },
          {
            "name": "TimeEnd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "expression": "Pivotted[Time] + TIME(0,15,0)",
            "formatString": "hh:nn",
            "isDataTypeInferred": true,
            "lineageTag": "a5438894-ac1e-4cf3-a8c6-f9b69cc5b14c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "RELATED('Weekday sort'[Sort order])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "30f9018f-dcba-4f2d-9f51-d8af076718ee",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Parent Activity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d42cd86b-9bef-4c7f-8c34-f18cd20cae7a",
            "sourceColumn": "Parent Activity",
            "summarizeBy": "none"
          },
          {
            "name": "Child 1 Activity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "831f19e4-f26e-4cb5-9331-4dfdb2a24aba",
            "sourceColumn": "Child 1 Activity",
            "summarizeBy": "none"
          },
          {
            "name": "Child 2 Activity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9d0635db-3a1e-44d5-936a-8d4eea6b3176",
            "sourceColumn": "Child 2 Activity",
            "summarizeBy": "none"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "f39e39c3-679f-44ea-845e-3e5679e9ba90",
            "sortByColumn": "Day Sort",
            "sourceColumn": "Day",
            "summarizeBy": "none"
          },
          {
            "name": "IsWork",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a08ad55d-dd63-4b9d-9442-bf0f260e4fde",
            "sourceColumn": "IsWork",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Week Start Hierarchy",
            "levels": [
              {
                "name": "Week Start - Sort",
                "column": "Week Start - Sort",
                "lineageTag": "07c9d45d-cac9-492f-ba78-203d8d34cb6c",
                "ordinal": 0
              }
            ],
            "lineageTag": "6c640378-28c7-4e1a-8662-f5a67da49b1e"
          },
          {
            "name": "Activity Hierarchy",
            "levels": [
              {
                "name": "Parent Activity",
                "column": "Parent Activity",
                "lineageTag": "26680d27-cd7f-40cb-b2b3-493a8a30752a",
                "ordinal": 0
              },
              {
                "name": "Child 1 Activity",
                "column": "Child 1 Activity",
                "lineageTag": "24f450d6-bd5e-4645-a866-886c68b9eea5",
                "ordinal": 1
              },
              {
                "name": "Child 2 Activity",
                "column": "Child 2 Activity",
                "lineageTag": "b3431586-cf70-4bfe-aee8-25d81d54f46b",
                "ordinal": 2
              }
            ],
            "lineageTag": "01c68cda-5c17-4172-aad0-956253005050"
          }
        ],
        "lineageTag": "d6151326-a015-4539-b0e5-54347087b791",
        "measures": [
          {
            "name": "TimeSpent",
            "expression": [
              "CALCULATE(",
              "    COUNT(Pivotted[Time])/4",
              ")"
            ],
            "formatString": "0.00",
            "lineageTag": "72362d49-589e-4229-8757-02193ce239c1"
          },
          {
            "name": "Excess Accrued",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    [TimeSpent] - DISTINCTCOUNT(Pivotted[Week Start - Sort]) *33.75",
              ")"
            ],
            "lineageTag": "4519addd-bea4-4ece-a857-17d4c97eacf4"
          }
        ],
        "partitions": [
          {
            "name": "Pivotted-f4aad6be-2088-4fe3-88f4-ad2d98e59d88",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"C:\\Users\\JackMacCormick\\OneDrive - Diabetes Australia\\Documents\\_Times\\Records\"),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File\", each #\"Transform File\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File\", Table.ColumnNames(#\"Transform File\"(#\"Sample File\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"Time\", type time}, {\"Monday\", type text}, {\"Tuesday\", type text}, {\"Wednesday\", type text}, {\"Thursday\", type any}, {\"Friday\", type any}, {\"Saturday\", type any}, {\"Sunday\", type any}, {\"Notes\", type any}}),",
                "    #\"Rename - weekday start\" = Table.RenameColumns(#\"Changed Type\",{{\"Source.Name\", \"Week Start\"}}),",
                "    #\"reduce filename to wk start\" = Table.TransformColumns(#\"Rename - weekday start\", {{\"Week Start\", each Text.BetweenDelimiters(_, \" \", \".\"), type text}}),",
                "    #\"Duplicated - weekday start\" = Table.DuplicateColumn(#\"reduce filename to wk start\", \"Week Start\", \"Week Start - Copy\"),",
                "    #\"rename - weekday as sortable\" = Table.RenameColumns(#\"Duplicated - weekday start\",{{\"Week Start - Copy\", \"Week Start - Sort\"}}),",
                "    #\"Reordered - weekday sort to front\" = Table.ReorderColumns(#\"rename - weekday as sortable\",{\"Week Start\", \"Week Start - Sort\", \"Time\", \"Monday\", \"Tuesday\", \"Wednesday\", \"Thursday\", \"Friday\", \"Saturday\", \"Sunday\", \"Notes\"}),",
                "    #\"Changed Type - weekday to date\" = Table.TransformColumnTypes(#\"Reordered - weekday sort to front\",{{\"Week Start\", type date}}),",
                "    #\"Removed - notes\" = Table.RemoveColumns(#\"Changed Type - weekday to date\",{\"Notes\"}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Removed - notes\", {\"Week Start\", \"Time\", \"Week Start - Sort\"}, \"Day\", \"Parent Activity\"),",
                "    #\"Lowercased - unpivoted\" = Table.TransformColumns(#\"Unpivoted Other Columns\",{{\"Parent Activity\", Text.Lower, type text}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Lowercased - unpivoted\", \"Parent Activity\", Splitter.SplitTextByDelimiter(\"-\", QuoteStyle.Csv), {\"Parent Activity\", \"Child 1 Activity\", \"Child 2 Activity\"}),",
                "    #\"Changed - splits to text\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"Parent Activity\", type text}, {\"Child 1 Activity\", type text}, {\"Child 2 Activity\", type text}}),",
                "    #\"Trimmed - splits\" = Table.TransformColumns(#\"Changed - splits to text\",{{\"Parent Activity\", Text.Trim, type text}, {\"Child 1 Activity\", Text.Trim, type text}, {\"Child 2 Activity\", Text.Trim, type text}}),",
                "    #\"Cleaned - splits\" = Table.TransformColumns(#\"Trimmed - splits\",{{\"Parent Activity\", Text.Clean, type text}, {\"Child 1 Activity\", Text.Clean, type text}, {\"Child 2 Activity\", Text.Clean, type text}}),",
                "    #\"Added iswork\" = Table.AddColumn(#\"Cleaned - splits\", \"IsWork\", each if [Parent Activity] <> \"lunch\" then \"Work\" else \"Lunch\")",
                "in",
                "    #\"Added iswork\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_b1b8f686-946b-4700-b7d7-a0032341467f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8aa20ed7-8e12-4d81-ab83-f5fde3b711a3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4f1ac9ca-66e1-4724-bc51-12f0cdae40af",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "abc7e214-fdf2-4a20-ad03-52aa20cca2f8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "39dca368-a2ae-409e-882d-96ef864bcc58",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d2881502-27df-4a11-9737-80c8f388b7cc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0d7b6673-69e6-4f31-88f4-ef852089b412",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9e9bb10b-870f-4b62-9faa-4494d1f6b809",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a8adfc99-3fb1-4ad8-a91a-051aefd6b2f1",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6f160d08-8688-49bc-b5a8-a495cd6e2846",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "4f8e4e28-573a-48dc-aded-ceb48a575b85",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "69d658a2-2506-485c-8d8f-91ae9071a021",
                "ordinal": 3
              }
            ],
            "lineageTag": "13d09a90-b880-42f6-afdc-d52605f79cb0"
          }
        ],
        "isHidden": true,
        "lineageTag": "828dfdf6-aa08-4574-b88d-b4cbdff98e69",
        "partitions": [
          {
            "name": "LocalDateTable_b1b8f686-946b-4700-b7d7-a0032341467f-e87b09b4-5a79-4cad-b4b3-b518370ea57d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Pivotted'[Week Start])), 1, 1), Date(Year(MAX('Pivotted'[Week Start])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Weekday sort",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "87e75270-5438-42d3-b4ed-f7180776b8e8",
            "sortByColumn": "Sort order",
            "sourceColumn": "Day",
            "summarizeBy": "none"
          },
          {
            "name": "Sort order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c7ea2080-72af-4ecf-8cab-98ab83da06ab",
            "sourceColumn": "Sort order",
            "summarizeBy": "none"
          },
          {
            "name": "Weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "741fb428-7a1a-4185-98d0-a03ac14952c7",
            "sourceColumn": "Weekday",
            "summarizeBy": "none"
          }
        ],
        "description": "Monday :: Sunday in order",
        "lineageTag": "39fc2549-dc34-4219-bec2-08846b0890ce",
        "partitions": [
          {
            "name": "Weekday sort-19e0d3d9-2015-481f-8bb0-fb2fb2eb6a3f",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8s3PS0msVNJRMgTikKBQV6VYnWilkNLUYoiwEbJweGpKHkzCGEV9RmkRVNwEWdytKBMiaoosGpxYUloEETcDYjdHn2CoRCnUMeYI4VgA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Day = _t, #\"Sort order\" = _t, Weekday = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Day\", type text}, {\"Sort order\", Int64.Type}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Changed Type\",{{\"Weekday\", type logical}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}