{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"YourOrg issues\",\"FetchPage\",\"FetchPages\",\"GenerateByPage\",\"URL\",\"Status Ranks\",\"Issue Families\",\"Issue Types\",\"Priorities\",\"Environments Lookup\",\"Status Codes\",\"DateDimension\",\"Server\",\"Database\",\"Report last refresh\",\"MeasuresTable\",\"Projects\",\"Fixes\",\"Devs\",\"Linked Issues\",\"Duplicate Check\",\"Uncoded Statuses\",\"JIRA API return\",\"JIRA Lookup tables\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.122.746.0 (23.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "FetchPage",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    FetchPage = (url as text, pageSize as number, skipRows as number) as table =>",
          "    let",
          "        //Here is where you run the code that will return a single page",
          "        contents = Web.Contents(",
          "            URL",
          "            , [RelativePath = \"/rest/api/2/search\"",
          "            , Query = [maxResults= Text.From(pageSize), startAt = Text.From(skipRows)]",
          "            ]",
          "        )",
          "        , json = Json.Document(contents)",
          "        , Value = json[issues]",
          "        , table = Table.FromList(Value, Splitter.SplitByNothing(), null, null, ExtraValues.Error)",
          "    in",
          "        table meta [skipRows = skipRows + pageSize, total = 100]",
          "in",
          "    FetchPage"
        ],
        "kind": "m",
        "lineageTag": "817bf858-ee70-40ab-a8a4-fc185ebf8a0b",
        "queryGroup": "02 API query\\02.1 Functions"
      },
      {
        "name": "FetchPages",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    FetchPages = (url as text, pageSize as number) => ",
          "let ",
          "    Source = GenerateByPage(",
          "    (previous) =>",
          "    let",
          "        skipRows = if previous = null then 0 else Value.Metadata(previous)[skipRows],",
          "        totalItems = if previous = null then 0 else Value.Metadata(previous)[total],",
          "        table = if previous = null or Table.RowCount(previous) = pageSize then ",
          "                    FetchPage(url, pageSize, skipRows) ",
          "\t\telse null",
          "    in table,",
          "    ",
          "    type table [Column1])",
          "in",
          "    Source",
          "in",
          "    FetchPages"
        ],
        "kind": "m",
        "lineageTag": "acf45744-d51a-4764-8d50-4564e22f9b0a",
        "queryGroup": "02 API query\\02.1 Functions"
      },
      {
        "name": "GenerateByPage",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "//Query Name: GenerateByPage",
          "let",
          "    Source = (getNextPage as function, optional tableType as type) as table =>",
          "    let",
          "        listOfPages = List.Generate(",
          "            () => getNextPage(null),",
          "            (lastPage) => lastPage <> null,",
          "            (lastPage) => getNextPage(lastPage)",
          "            ),",
          "        tableOfPages = Table.FromList(listOfPages, Splitter.SplitByNothing(), {\"Column1\"}),",
          "        firstRow = tableOfPages{0}?,",
          "        keys = if tableType = null then Table.ColumnNames(firstRow[Column1])",
          "               else Record.FieldNames(Type.RecordFields(Type.TableRow(tableType))),",
          "        appliedType = if tableType = null then Value.Type(firstRow[Column1]) else tableType",
          "    in",
          "        if tableType = null and firstRow = null then",
          "            Table.FromRows({})",
          "        else",
          "        Value.ReplaceType(Table.ExpandTableColumn(tableOfPages, \"Column1\", keys), appliedType)",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "ef1a849c-4751-4d21-90ae-50b628977075",
        "queryGroup": "02 API query\\02.1 Functions"
      },
      {
        "name": "URL",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": "Jira's URL",
        "expression": "\"YOUR_JIRA_DOMAIN\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "ed83b390-9817-4fd6-bc11-dfe2487610af",
        "queryGroup": "00 Params"
      },
      {
        "name": "Status Ranks",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "description": "Sort order and a hierarchy added manually, feeds into a merge",
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"lVZNc5swEP0rGp9zSD/SjI84pGlm2prBpD5kclBhY6sWEpXAHv/7rhAQSEEyBwvN7ltpJb236+fnRSD0CRRki6tFKAXgZ3mLQxI/3S9ertB/oqxkYkeColDySDk6O9uq0kyA1mj7hL+vwfeNjdo2gFepCJ0T2CFCSJlmUsyMuv+FkQWX5xxEiZgmEZx9no5IQDcgLzyK1+EcfAxaViqFecfYJA8zj2EiZqT1FCQzNzAR/g36766ropDKtfiKpgcujf1t9mGACOEIXBYmSeJHt7tLQfqBCdDckUUEIrP2qXUbu3ZBuEwPkJHVmazLPSgDtSacfRlA76hIgdcOO7Xz5bIvu77HgeIo2UnpoldPe1uBNcK+ABjDH0hLT0odesvKfaboSfjgnAnvmiVl6CCBoPysmXmI7WOE482QLajlGI4MTmjuJrf/YQyPCRMkUnKnrBDHlouq35zpveOCZV5wKB1XZ43jPkVfjTgSSUKJ34+DvR+oYZGtIH8rpsAweSrRrVQHc57CfZ7HgSwmQJ3gmTmbAdLSluHRJVtQUxbGd/Xc88/6mex4PfCsBfkmeeYSL9UOjnccGH1eAEU8iLoyvIH8JTziVIjpy4gUcJYzQdXZR2bTObhDljHTB/ID09lRBwM3qSwuZNEGi5KRd1283xFl4vabhkCGb+y/pZbz49zHVnPZKl078mPb9vVO9jMC3UzrN7600qXM6x7gbat3eyp2MOPP1cs/\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [status.name = _t, Family = _t, #\"Status Rank\" = _t, #\"Is terminal\" = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"status.name\", type text}, {\"Family\", type text}, {\"Status Rank\", Int64.Type}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "3c8ddbd3-d303-4452-867b-ba344665d548",
        "queryGroup": "03 Supporting Tables\\03.1 Staging\\0.3.1.1 Manual mappings"
      },
      {
        "name": "Server",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": "Server to connect to",
        "expression": "\"SourceServer\" meta [IsParameterQuery=true, List={\"SourceServer\"}, DefaultValue=\"SourceServer\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "3b5e9a90-8584-4400-8dd8-eab83f8410c4",
        "queryGroup": "00 Params"
      },
      {
        "name": "Database",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": "Which instance of the DB should we connect to?",
        "expression": "\"Your_PROD\" meta [IsParameterQuery=true, List={\"Your_PROD\", \"Your_Dev\", \"Your_UAT\"}, DefaultValue=\"Your_PROD\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "a17e5f19-2be4-4b05-b913-748c6f717800",
        "queryGroup": "00 Params"
      },
      {
        "name": "JIRA Lookup tables",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "description": "All the expandable fields, stashed here for easy reference later",
        "expression": [
          "let",
          "    Source = FetchPages(\"\", 100),",
          "    #\"Expanded records\" = Table.ExpandRecordColumn(Source, \"Column1\", {\"expand\", \"id\", \"self\", \"key\", \"fields\"}, {\"expand\", \"issue ID\", \"issue address\", \"issue key\", \"fields\"}),",
          "    #\"Expanded fields\" = Table.ExpandRecordColumn(#\"Expanded records\", \"fields\", {\"parent\", \"fixVersions\", \"resolution\", \"lastViewed\", \"priority\", \"labels\", \"timeestimate\", \"aggregatetimeoriginalestimate\", \"versions\", \"issuelinks\", \"assignee\", \"status\", \"components\", \"aggregatetimeestimate\", \"creator\", \"subtasks\", \"reporter\", \"aggregateprogress\", \"progress\", \"votes\", \"issuetype\", \"timespent\", \"project\", \"aggregatetimespent\", \"resolutiondate\", \"workratio\", \"watches\", \"created\", \"updated\", \"timeoriginalestimate\", \"description\", \"summary\", \"environment\", \"duedate\"}, {\"parent\", \"fixVersions\", \"resolution\", \"lastViewed\", \"priority\", \"labels\", \"timeestimate\", \"aggregatetimeoriginalestimate\", \"versions\", \"issuelinks\", \"assignee\", \"status\", \"components\", \"aggregatetimeestimate\", \"creator\", \"subtasks\", \"reporter\", \"aggregateprogress\", \"progress\", \"votes\", \"issuetype\", \"timespent\", \"project\", \"aggregatetimespent\", \"resolutiondate\", \"workratio\", \"watches\", \"created\", \"updated\", \"timeoriginalestimate\", \"description\", \"summary\", \"environment\", \"duedate\"}),",
          "    // Resolution: Worse version of status",
          "    // Description: wayyyy to much text, dont need that in report's memory",
          "    // Expand: fields the API can get",
          "    // Watches: don't need to know/report it",
          "    // Versions: would bloat report",
          "    // Linked Issues: would bloat report",
          "    // Subtask: already have parent task if relevant, would bloat",
          "    // Votes: not using votes here",
          "    #\"Removed unneccesary fields\" = Table.RemoveColumns(#\"Expanded fields\",{\"expand\", \"watches\", \"versions\", \"issuelinks\", \"subtasks\", \"votes\", \"resolution\", \"description\"}),",
          "    // Extracted to records from List",
          "    #\"Expanded components\" = Table.ExpandListColumn(#\"Removed unneccesary fields\", \"components\"),",
          "    #\"Expanded components1\" = Table.ExpandRecordColumn(#\"Expanded components\", \"components\", {\"name\"}, {\"components.name\"}),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Expanded components1\",{\"priority\", \"labels\", \"fixVersions\", \"assignee\", \"status\", \"progress\", \"issuetype\", \"project\"})",
          "in",
          "    #\"Removed Other Columns\""
        ],
        "kind": "m",
        "lineageTag": "32342a4d-5743-4940-a58f-93b3aec6193a",
        "queryGroup": "02 API query\\02.3 Lookup table reference"
      },
      {
        "name": "Issue Families",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"bVRLb9swDP4rRE4bkAbFLjt36Q7tUKBrcut6oGXa0SJLrh7x/O9Hyo/ETS+2KPH58SNfX1d3EFwVO/QEJZ3IuLYhGyFiOK7Wq3s6wX4+rt7WYtB6VxhqwHkg753f8OuPVI/fQSc0aMwaSh2itipCq0kRuAo6549iMHrNPzHZRec1BYge1RGqxEbaWTQ69hKoIozJ8zv9a/kXqAQMkAJ5qB2aIC7FRT//hzwKXQ9aQS4hHjCCJSo5kIOCoPDuSBZK19kNbD1HYc9FD4/aI+wmZG5YAayLQKWOkk5JhiJJ0J+tVh9iCnbivnQqZTARQh8iNWsge9LeWbldix+GUnE1Au+ojFI2y7+s6wyVNWWnz979JZVD87H22MCLzgBe/nJ4CzqERBD7lqDKuSod2GmOMp4vj2K1PxAwrMnEIE1C2FOIsMVA0qPpDC+DyniXLfFz/oRU3FxwaLcQR5watAkNRBKO1Nwhai+jXUZhQummNQTvSbSdXXO670l7McTpEW3oyG/gIeRmoQUcWMR0nRj9e3RwBfHI2SVTM2H+pNvbb98DtOjjgI5BXzOnxGUm3rm6mc93oBJzrrnqBkYsBMsWozpw+gIJ38GzyJPwIEYf6KQyO9fQuFJXeSg8Rc24IxynSrJnTlMrw5oH14lhnXRJQFFtLovOqneD6hUYuU+tcX1u5rwBppsxM2mBdCtPVeWMcV2Ah/3uKWNXiSghX3eZ/W+wI3/SiiY7QS6/ZHf3FJTXhZRznv6xy5TTuIEuB1rsBiFe75LsBR4QocOXmQ0lE8PWibv1VUbk7GoxsFdTP2b5hBbrrL4oYntAW9Myd5bm68Vcsfw8bMuL7bj9lBieWudzAR/3cIDAtelKq5lBXBwajh9yXWIIn6zqXSa0jrKrRz53OjLpzhSWx4HBCwK//Qc=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [issuetype.description = _t, issuetype = _t, Family = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"issuetype.description\", type text}, {\"issuetype\", type text}, {\"Family\", type text}}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Family\", \"Issue type family\"}, {\"issuetype\", \"Issue type\"}, {\"issuetype.description\", \"Issue type description\"}})",
          "in",
          "    #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "a9d59c10-d70f-485e-86a6-f9d5e82e5165",
        "queryGroup": "03 Supporting Tables\\03.1 Staging\\0.3.1.1 Manual mappings"
      },
      {
        "name": "Duplicate Check",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = #\"YourOrg issues\",",
          "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"issue ID\"}),",
          "    #\"Grouped Rows\" = Table.Group(#\"Removed Other Columns\", {\"issue ID\"}, {{\"Instance count\", each Table.RowCount(_), Int64.Type}}),",
          "    #\"Added is duped\" = Table.AddColumn(#\"Grouped Rows\", \"No Dups\", each [Instance count] = 1),",
          "    #\"Grouped on no dups\" = Table.Group(#\"Added is duped\", {\"No Dups\"}, {{\"Instance count\", each Table.RowCount(Table.Distinct(_)), Int64.Type}})",
          "in",
          "    #\"Grouped on no dups\""
        ],
        "kind": "m",
        "lineageTag": "9c4f5d95-8468-429d-b710-76b23652c1a5",
        "queryGroup": "98 Quality check"
      },
      {
        "name": "Uncoded Statuses",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "description": [
          "Can happen when a new board is created with new statues, if those statuses don't name match existing ones. ",
          "",
          "Ideally projects are all set up by JIRA admins, and use org provided statuses, but this is not enforceable"
        ],
        "expression": [
          "let",
          "    Source = #\"Status Codes\",",
          "    #\"Kept Blank Rows\" = Table.SelectRows(Source, each ([Family] = \"\" or [Family] = null)),",
          "    // This col comes from a join against a manually created status ranking table. Any blanks here haven't been put into that table yet",
          "    #\"Grouped Rows\" = Table.Group(#\"Kept Blank Rows\", {\"Status\"}, {{\"Count\", each Table.RowCount(_), Int64.Type}}),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Grouped Rows\",{\"Status\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Other Columns\",{{\"Status\", \"Uncoded status\"}})",
          "in",
          "    #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "a47403bd-5d0b-4654-b325-1efbd92e2e6b",
        "queryGroup": "98 Quality check"
      },
      {
        "name": "JIRA API return",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "description": "Raw output of the JIRA API call",
        "expression": [
          "let",
          "    Source = FetchPages(\"\", 100)",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "114ca295-ab4e-4dcc-af83-3a4ad41b1cbd",
        "queryGroup": "02 API query\\02.2 Query Return"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "00 Params"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "01 Utilities"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "6"
          }
        ],
        "folder": "99 Testing"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "5"
          }
        ],
        "folder": "98 Quality check"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "03 Supporting Tables"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "4"
          }
        ],
        "folder": "04 Finalised Tables"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "02 API query\\02.1 Functions"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "description": "All the supporting tables, pulled from 02.3 `JIRA Lookup tables`",
        "folder": "03 Supporting Tables\\03.1 Staging\\03.2 Lookup tables"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "03 Supporting Tables\\03.1 Staging"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "02 API query"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "02 API query\\02.2 Query Return"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "description": [
          "These use a manual mapping, which needs to be updated if there are new statuses or new issue type families.",
          "Families are an abstract category added to handle similar statuses"
        ],
        "folder": "03 Supporting Tables\\03.1 Staging\\0.3.1.1 Manual mappings"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "description": "All the expandable columns containing further tables",
        "folder": "02 API query\\02.3 Lookup table reference"
      }
    ],
    "relationships": [
      {
        "name": "78f27c15-3022-4adb-a352-4e5bfa1b8e4b",
        "fromColumn": "updated",
        "fromTable": "YourOrg issues",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d35d2461-f30e-4251-8eae-e26f037d9476"
      },
      {
        "name": "f8d7c440-931b-4826-9122-7c2ea3ea726b",
        "fromColumn": "lastViewed",
        "fromTable": "YourOrg issues",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_6ea7635f-d568-4e29-b629-3306888ad0be"
      },
      {
        "name": "17fc446e-b2a7-4823-9ca9-f3e62c08e882",
        "fromColumn": "duedate",
        "fromTable": "YourOrg issues",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_988b7735-89b6-422d-aa32-ce3c2747d889"
      },
      {
        "name": "0450073e-123d-491d-8c46-ff42e75eea1d",
        "fromColumn": "environment",
        "fromTable": "YourOrg issues",
        "toColumn": "environment",
        "toTable": "Environments Lookup"
      },
      {
        "name": "96f5d0f5-7ade-4adc-ba2d-a8bc4520a265",
        "fromColumn": "created",
        "fromTable": "YourOrg issues",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_bf00ef03-f29e-4420-b353-30eeec4d0eaa"
      },
      {
        "name": "2519a7b8-8244-43fe-8a6b-51318cd20abd",
        "fromColumn": "Report last refreshed",
        "fromTable": "Report last refresh",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3860530a-946d-4dbd-a261-9cddf2ac696b"
      },
      {
        "name": "011ca8ef-f679-4eb7-b44a-a17d84f80dc9",
        "fromColumn": "updated - Date",
        "fromTable": "YourOrg issues",
        "isActive": false,
        "toColumn": "TheDate",
        "toTable": "DateDimension"
      },
      {
        "name": "d5da87d9-3da6-4d8f-bff0-19ea6076f992",
        "fromColumn": "Resolution Date Improved - Date",
        "fromTable": "YourOrg issues",
        "isActive": false,
        "toColumn": "TheDate",
        "toTable": "DateDimension"
      },
      {
        "name": "6da0cc40-abd2-4c06-84a2-809ce862fb2c",
        "fromColumn": "releaseDate",
        "fromTable": "Fixes",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c2bb7f89-a9fe-4656-a0d6-e5399e5c4f08"
      },
      {
        "name": "9363bb38-2951-4ceb-ab8d-aa2f8f398bbb",
        "fromColumn": "status.id",
        "fromTable": "YourOrg issues",
        "toColumn": "id",
        "toTable": "Status Codes"
      },
      {
        "name": "632473e9-5fc9-445a-bf95-5b70749d2a7b",
        "fromColumn": "priority.id",
        "fromTable": "YourOrg issues",
        "toColumn": "id",
        "toTable": "Priorities"
      },
      {
        "name": "fe8dec41-957e-fecf-03e2-97b4e0041ecd",
        "fromColumn": "assignee.accountId",
        "fromTable": "YourOrg issues",
        "toColumn": "accountId",
        "toTable": "Devs"
      },
      {
        "name": "89486a14-8ad0-41d4-9c8f-14bf001c3b8c",
        "fromColumn": "project.id",
        "fromTable": "YourOrg issues",
        "toColumn": "id",
        "toTable": "Projects"
      },
      {
        "name": "c8cfaa35-059f-457c-9160-61a375b8e421",
        "fromColumn": "Resolution Date Improved",
        "fromTable": "YourOrg issues",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7ae11d14-c76b-45f3-8f69-4a03985e8149"
      },
      {
        "name": "ef9f80c8-3f8c-4562-8b49-991fbb281f53",
        "fromColumn": "created - Date",
        "fromTable": "YourOrg issues",
        "toColumn": "TheDate",
        "toTable": "DateDimension"
      },
      {
        "name": "152c4afd-80b2-ba1e-8f58-2f03f8bd11aa",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "issue key",
        "fromTable": "YourOrg issues",
        "toColumn": "Child key",
        "toTable": "Linked Issues"
      },
      {
        "name": "da9c952b-0ee3-4d44-b14a-14a00f5c9358",
        "fromColumn": "issuetype.id",
        "fromTable": "YourOrg issues",
        "toColumn": "id",
        "toTable": "Issue Types"
      }
    ],
    "sourceQueryCulture": "en-AU",
    "tables": [
      {
        "name": "DateTableTemplate_495f1d20-1f75-4d39-a98c-4dd3d7c8c3b0",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "72988f22-75cc-42b0-9e06-a828968ca46a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e9c9e580-4094-4bb4-bc93-fdba1b8be698",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "371ebdd3-c4a6-4a3f-83f7-c776ef0fbbea",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "83d61bcd-3b09-4909-9e06-f3b7001fef47",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "eb4e16b1-b1b2-470d-b8be-973764b9440a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ef59b5ab-4134-4591-9689-67fde3922805",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "adaa778a-597d-4572-ac27-bbcb3836ecc4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "58fe7b2b-9146-417f-a1cc-50d0f1125b77",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8d945055-7898-4205-b228-993639572fbf",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "77a0be1b-2c82-4c58-afcb-611bc21f16b5",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "80bd8910-05b8-45de-bdda-72681fb9ad47",
                "ordinal": 3
              }
            ],
            "lineageTag": "115a308e-4213-4da8-ad3d-bb837fa91602"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "e0958a36-4a67-407f-9822-a42b73f665d1",
        "partitions": [
          {
            "name": "DateTableTemplate_495f1d20-1f75-4d39-a98c-4dd3d7c8c3b0-cc570a6b-4ad2-4e87-a334-c422e4b0ed80",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "YourOrg issues",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "timespent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e10939b9-eeee-4d01-9f95-0e9e9e28003a",
            "sourceColumn": "timespent",
            "summarizeBy": "none"
          },
          {
            "name": "project.id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79238c10-9bd1-4bb7-87a9-9b586e52b4c9",
            "sourceColumn": "project.id",
            "summarizeBy": "none"
          },
          {
            "name": "aggregatetimespent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "8f50c6af-342b-470b-835b-61b388a33471",
            "sourceColumn": "aggregatetimespent",
            "summarizeBy": "sum"
          },
          {
            "name": "workratio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8f771c8-1947-4dfb-ac38-dd0953dd2d33",
            "sourceColumn": "workratio",
            "summarizeBy": "none"
          },
          {
            "name": "lastViewed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "b6d6ec98-3c7c-4ad5-8b26-ae760b45c3dc",
            "sourceColumn": "lastViewed",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_6ea7635f-d568-4e29-b629-3306888ad0be"
                },
                "isDefault": true,
                "relationship": "f8d7c440-931b-4826-9122-7c2ea3ea726b"
              }
            ]
          },
          {
            "name": "created",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "94a8789a-e901-48dd-8159-4fd06499e21f",
            "sourceColumn": "created",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_bf00ef03-f29e-4420-b353-30eeec4d0eaa"
                },
                "isDefault": true,
                "relationship": "96f5d0f5-7ade-4adc-ba2d-a8bc4520a265"
              }
            ]
          },
          {
            "name": "timeestimate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89f399ed-6b6a-4f29-9c55-22dff1bf8708",
            "sourceColumn": "timeestimate",
            "summarizeBy": "none"
          },
          {
            "name": "aggregatetimeoriginalestimate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "f60ee873-630d-400b-b70a-01bdfb798888",
            "sourceColumn": "aggregatetimeoriginalestimate",
            "summarizeBy": "sum"
          },
          {
            "name": "updated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d79d502c-da46-4f6f-8ab5-67bcf5ff9ec7",
            "sourceColumn": "updated",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_d35d2461-f30e-4251-8eae-e26f037d9476"
                },
                "isDefault": true,
                "relationship": "78f27c15-3022-4adb-a352-4e5bfa1b8e4b"
              }
            ]
          },
          {
            "name": "timeoriginalestimate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "297a2d90-e4e8-44c5-b2b1-fe2218c85e89",
            "sourceColumn": "timeoriginalestimate",
            "summarizeBy": "none"
          },
          {
            "name": "aggregatetimeestimate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "66baaddf-345b-496d-89c1-31939250da8f",
            "sourceColumn": "aggregatetimeestimate",
            "summarizeBy": "sum"
          },
          {
            "name": "summary",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23ee81b9-cb3a-44c2-8347-61e583f425e5",
            "sourceColumn": "summary",
            "summarizeBy": "none"
          },
          {
            "name": "reporter.name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ce0fac3-9198-4d48-a153-2b4d9e0a3499",
            "sourceColumn": "reporter.name",
            "summarizeBy": "none"
          },
          {
            "name": "reporter.emailAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e36f08f1-7d89-4f01-acd8-fc1690c2ffe9",
            "sourceColumn": "reporter.emailAddress",
            "summarizeBy": "none"
          },
          {
            "name": "reporter.displayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c479bed2-3c6e-450f-80af-ebea26f80947",
            "sourceColumn": "reporter.displayName",
            "summarizeBy": "none"
          },
          {
            "name": "reporter.active",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "170ec28b-8053-40eb-9888-dee786ff7a7c",
            "sourceColumn": "reporter.active",
            "summarizeBy": "none"
          },
          {
            "name": "aggregateprogress.progress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02d0b01b-2c8d-4095-94a5-65e68ee31ffe",
            "sourceColumn": "aggregateprogress.progress",
            "summarizeBy": "none"
          },
          {
            "name": "aggregateprogress.total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "37a5a702-5d71-41ee-8f97-fe6d052f6601",
            "sourceColumn": "aggregateprogress.total",
            "summarizeBy": "none"
          },
          {
            "name": "environment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aec34014-563a-4aa7-a2d6-f782cb078d2e",
            "sourceColumn": "environment",
            "summarizeBy": "none"
          },
          {
            "name": "duedate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy/mm/dd",
            "lineageTag": "bded1d46-48cc-4ba3-aecc-4b032d5dde9d",
            "sourceColumn": "duedate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_988b7735-89b6-422d-aa32-ce3c2747d889"
                },
                "isDefault": true,
                "relationship": "17fc446e-b2a7-4823-9ca9-f3e62c08e882"
              }
            ]
          },
          {
            "name": "progress.progress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "59c77c6e-c165-4ad4-8a49-e5c09a2c0e9f",
            "sourceColumn": "progress.progress",
            "summarizeBy": "none"
          },
          {
            "name": "progress.total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa93382d-c064-4dce-be23-27b4d7129836",
            "sourceColumn": "progress.total",
            "summarizeBy": "none"
          },
          {
            "name": "parent.id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "580bd122-f09e-493d-ac70-9d3bf6edf097",
            "sourceColumn": "parent.id",
            "summarizeBy": "none"
          },
          {
            "name": "Days since Created",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cc8f1933-467e-4584-af03-5d66ff976a2a",
            "sourceColumn": "Days since Created",
            "summarizeBy": "average"
          },
          {
            "name": "Days since Modified",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dee04062-4c60-487a-9b31-f762e8c80dc3",
            "sourceColumn": "Days since Modified",
            "summarizeBy": "average"
          },
          {
            "name": "issue ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a98a8bec-1d8c-4703-a8a5-5fc304cc6feb",
            "sourceColumn": "issue ID",
            "summarizeBy": "none"
          },
          {
            "name": "issue address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7728aca-9df6-41a0-9aa5-8ad1805af8ab",
            "sourceColumn": "issue address",
            "summarizeBy": "none"
          },
          {
            "name": "issue key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c39b355a-a7c0-43c4-b802-fb0ebcff3af5",
            "sourceColumn": "issue key",
            "summarizeBy": "none"
          },
          {
            "name": "parent.key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "238450ee-40d7-4ba6-860d-03b6ef098a81",
            "sourceColumn": "parent.key",
            "summarizeBy": "none"
          },
          {
            "name": "status.id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "824d4deb-e10f-4f01-885e-bc9077b20a3f",
            "sourceColumn": "status.id",
            "summarizeBy": "none"
          },
          {
            "name": "creator.accountId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdf703e3-89f3-4b7d-8108-5434f4ee8f62",
            "sourceColumn": "creator.accountId",
            "summarizeBy": "none"
          },
          {
            "name": "creator.displayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4adbc08-4bfe-47d0-911f-d8285cffc258",
            "sourceColumn": "creator.displayName",
            "summarizeBy": "none"
          },
          {
            "name": "Resolution Date Improved",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5e5cebbd-478b-4c96-a4f2-27885e573dad",
            "sourceColumn": "Resolution Date Improved",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_7ae11d14-c76b-45f3-8f69-4a03985e8149"
                },
                "isDefault": true,
                "relationship": "c8cfaa35-059f-457c-9160-61a375b8e421"
              }
            ]
          },
          {
            "name": "created - Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy/mm/dd",
            "lineageTag": "e19930e4-58d2-4db4-b114-11e392c28fef",
            "sourceColumn": "created - Date",
            "summarizeBy": "none"
          },
          {
            "name": "updated - Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy/mm/dd",
            "lineageTag": "a168633b-d96e-4478-96a1-d601f2a5f678",
            "sourceColumn": "updated - Date",
            "summarizeBy": "none"
          },
          {
            "name": "Resolution Date Improved - Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy/mm/dd",
            "lineageTag": "aeebea60-7670-44d7-b514-4c08f3ed02fc",
            "sourceColumn": "Resolution Date Improved - Date",
            "summarizeBy": "none"
          },
          {
            "name": "priority.id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e885400a-aad8-4a36-97c9-863d4b5e6188",
            "sourceColumn": "priority.id",
            "summarizeBy": "none"
          },
          {
            "name": "assignee.accountId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66738d6e-19b2-4cef-9b43-b342de853ed7",
            "sourceColumn": "assignee.accountId",
            "summarizeBy": "none"
          },
          {
            "name": "issuetype.id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03d10392-98a6-4827-8e7b-c852e4bf1dd0",
            "sourceColumn": "issuetype.id",
            "summarizeBy": "none"
          },
          {
            "name": "issuetype.isSubTask",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3bc4f51-6832-4e5b-994a-54dcbf700a8b",
            "sourceColumn": "issuetype.isSubTask",
            "summarizeBy": "none"
          },
          {
            "name": "Days to Resolve",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9c5578e8-7ca9-440d-839f-bb498d4c7872",
            "sourceColumn": "Days to Resolve",
            "summarizeBy": "sum"
          },
          {
            "name": "fixVersions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20196cb4-e69a-478a-bb99-ab3c6a0d9155",
            "sourceColumn": "fixVersions",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4adae639-dbf3-4b0d-8016-e6bce3b421c3",
        "partitions": [
          {
            "name": "YourOrg issues",
            "mode": "import",
            "queryGroup": "04 Finalised Tables",
            "source": {
              "expression": [
                "let",
                "    Source = #\"JIRA API return\",",
                "    #\"Expanded records\" = Table.ExpandRecordColumn(Source, \"Column1\", {\"expand\", \"id\", \"self\", \"key\", \"fields\"}, {\"expand\", \"issue ID\", \"issue address\", \"issue key\", \"fields\"}),",
                "    #\"Expanded fields\" = Table.ExpandRecordColumn(#\"Expanded records\", \"fields\", {\"parent\", \"fixVersions\", \"resolution\", \"lastViewed\", \"priority\", \"labels\", \"timeestimate\", \"aggregatetimeoriginalestimate\", \"versions\", \"issuelinks\", \"assignee\", \"status\", \"components\", \"aggregatetimeestimate\", \"creator\", \"subtasks\", \"reporter\", \"aggregateprogress\", \"progress\", \"votes\", \"issuetype\", \"timespent\", \"project\", \"aggregatetimespent\", \"resolutiondate\", \"workratio\", \"watches\", \"created\", \"updated\", \"timeoriginalestimate\", \"description\", \"summary\", \"environment\", \"duedate\"}, {\"parent\", \"fixVersions\", \"resolution\", \"lastViewed\", \"priority\", \"labels\", \"timeestimate\", \"aggregatetimeoriginalestimate\", \"versions\", \"issuelinks\", \"assignee\", \"status\", \"components\", \"aggregatetimeestimate\", \"creator\", \"subtasks\", \"reporter\", \"aggregateprogress\", \"progress\", \"votes\", \"issuetype\", \"timespent\", \"project\", \"aggregatetimespent\", \"resolutiondate\", \"workratio\", \"watches\", \"created\", \"updated\", \"timeoriginalestimate\", \"description\", \"summary\", \"environment\", \"duedate\"}),",
                "    // Resolution: Worse version of status",
                "    // Description: wayyyy to much text, dont need that in report's memory",
                "    // Expand: fields the API can get",
                "    // Watches: don't need to know/report it",
                "    // Versions: would bloat report",
                "    // Linked Issues: would bloat report",
                "    // Subtask: already have parent task if relevant, would bloat",
                "    // Votes: not using votes here",
                "    #\"Removed unneccesary fields\" = Table.RemoveColumns(#\"Expanded fields\",{\"expand\", \"watches\", \"versions\", \"issuelinks\", \"subtasks\", \"votes\", \"resolution\", \"description\", \"labels\", \"components\"}),",
                "    #\"Filtered issue not null or blank\" = Table.SelectRows(#\"Removed unneccesary fields\", each [issue ID] <> null and [issue ID] <> \"\"),",
                "    #\"Expanded issuetype\" = Table.ExpandRecordColumn(#\"Filtered issue not null or blank\", \"issuetype\", {\"id\", \"subtask\"}, {\"issuetype.id\", \"issuetype.isSubTask\"}),",
                "    #\"Expanded project\" = Table.ExpandRecordColumn(#\"Expanded issuetype\", \"project\", {\"id\"}, {\"project.id\"}),",
                "    // Inner join so we exclude non-desired projects, i.e. Service Management",
                "    #\"Inner Join w/ Projects table\" = Table.NestedJoin(#\"Expanded project\", {\"project.id\"}, Projects, {\"id\"}, \"Projects\", JoinKind.Inner),",
                "    #\"Expanded priority\" = Table.ExpandRecordColumn(#\"Inner Join w/ Projects table\", \"priority\", {\"id\"}, {\"priority.id\"}),",
                "    #\"Expanded assignee\" = Table.ExpandRecordColumn(#\"Expanded priority\", \"assignee\", {\"accountId\"}, {\"assignee.accountId\"}),",
                "    #\"Expanded status\" = Table.ExpandRecordColumn(#\"Expanded assignee\", \"status\", {\"id\"}, {\"status.id\"}),",
                "    #\"Expanded reporter\" = Table.ExpandRecordColumn(#\"Expanded status\", \"reporter\", {\"name\", \"emailAddress\", \"displayName\", \"active\"}, {\"reporter.name\", \"reporter.emailAddress\", \"reporter.displayName\", \"reporter.active\"}),",
                "    #\"Expanded aggregateprogress\" = Table.ExpandRecordColumn(#\"Expanded reporter\", \"aggregateprogress\", {\"progress\", \"total\"}, {\"aggregateprogress.progress\", \"aggregateprogress.total\"}),",
                "    #\"Expanded progress\" = Table.ExpandRecordColumn(#\"Expanded aggregateprogress\", \"progress\", {\"progress\", \"total\"}, {\"progress.progress\", \"progress.total\"}),",
                "    #\"Expanded parent\" = Table.ExpandRecordColumn(#\"Expanded progress\", \"parent\", {\"id\", \"key\"}, {\"parent.id\", \"parent.key\"}),",
                "    #\"Expanded creator\" = Table.ExpandRecordColumn(#\"Expanded parent\", \"creator\", {\"accountId\", \"displayName\"}, {\"creator.accountId\", \"creator.displayName\"}),",
                "    #\"Changed Type duedate\" = Table.TransformColumnTypes(#\"Expanded creator\",{{\"duedate\", type date}}),",
                "    // Clean up for matching into lookup table",
                "    #\"Uppercased environment\" = Table.TransformColumns(Table.TransformColumnTypes(#\"Changed Type duedate\", {{\"environment\", type text}}, \"en-AU\"),{}),",
                "    #\"Replaced Environement blank -> null\" = Table.ReplaceValue(#\"Uppercased environment\",\"\",null,Replacer.ReplaceValue,{\"environment\"}),",
                "    #\"Merged w status\" = Table.NestedJoin(#\"Replaced Environement blank -> null\", {\"status.id\"}, #\"Status Codes\", {\"id\"}, \"Status Codes\", JoinKind.LeftOuter),",
                "    #\"Expanded status is terminal\" = Table.ExpandTableColumn(#\"Merged w status\", \"Status Codes\", {\"Is terminal\"}, {\"Status Codes.Is terminal\"}),",
                "    // Needed to add a way to infill resolved data for a few issue types which don't automatically create a resolution date in JIRA. Checks against the status codes table's `is terminal` col",
                "    // Using last modified instead where resolution = NULL",
                "    #\"Added Improved Resolution Date\" = Table.AddColumn(#\"Expanded status is terminal\", \"Resolution Date Improved\", each if (",
                "\t    [resolutiondate]  = null ",
                "\t    and [Status Codes.Is terminal] = true",
                "    ) then [updated] // if nothing found, just give the null",
                "    else [resolutiondate]),",
                "    #\"removed status is terminal\" = Table.RemoveColumns(#\"Added Improved Resolution Date\",{\"Status Codes.Is terminal\"}),",
                "    // LDS was overseas, Some org is in Canberra tz, another org is in Sydney TZ",
                "    #\"Changed Type time to timezoned\" = Table.TransformColumnTypes(#\"removed status is terminal\",{{\"lastViewed\", type datetimezone}, {\"updated\", type datetimezone}, {\"created\", type datetimezone}, {\"resolutiondate\", type datetimezone}, {\"Resolution Date Improved\", type datetimezone}}),",
                "    #\"Added days since mod\" = Table.AddColumn(#\"Changed Type time to timezoned\", \"Days since Modified\", each Duration.Days(DateTime.Date(DateTime.LocalNow()) - DateTime.Date([updated]))),",
                "    #\"Added days since created\" = Table.AddColumn(#\"Added days since mod\", \"Days since Created\", each Duration.Days(DateTime.Date(DateTime.LocalNow()) - DateTime.Date([created]))),",
                "    #\"Removed resolution date, replaced by improved version\" = Table.RemoveColumns(#\"Added days since created\",{\"resolutiondate\"}),",
                "    #\"Added Days taken to resolve\" = Table.AddColumn(#\"Removed resolution date, replaced by improved version\", \"Days to Resolve\", each Duration.Days(DateTime.Date([Resolution Date Improved]) - DateTime.Date([created]))),",
                "    #\"Changed resolved days to num\" = Table.TransformColumnTypes(#\"Added Days taken to resolve\",{{\"Days to Resolve\", Int64.Type}}),",
                "    #\"Duplicated created to date only\" = Table.DuplicateColumn(#\"Changed resolved days to num\", \"created\", \"created - Date\"),",
                "    #\"Duplicated updated to date only\" = Table.DuplicateColumn(#\"Duplicated created to date only\", \"updated\", \"updated - Date\"),",
                "    #\"Duplicated resolution to date only\" = Table.DuplicateColumn(#\"Duplicated updated to date only\", \"Resolution Date Improved\", \"Resolution Date Improved - Date\"),",
                "    #\"Changed duped datetimes to dates\" = Table.TransformColumnTypes(#\"Duplicated resolution to date only\",{{\"created - Date\", type date}, {\"updated - Date\", type date}, {\"Resolution Date Improved - Date\", type date}})",
                "in",
                "    #\"Changed duped datetimes to dates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_d35d2461-f30e-4251-8eae-e26f037d9476",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f7631eba-2e5a-4c79-9592-871c1092bc0d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "13d04595-9d74-4e6b-ab43-3ba1be182098",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "24694439-df82-4456-8bde-be185bd44cb4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "63dbaa3d-1722-4007-8fce-b7b34eff29f3",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "31846dc1-d094-4d0c-98ef-51d605b76d08",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7faaabc9-192f-4e9b-b9cb-a4d29989d3c9",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f47e3e34-087a-409a-9ea7-be545ebbf404",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "917c7383-0778-4040-8587-79921e1181c6",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b03ef1b7-88f3-4aae-be73-0d184aa75cf6",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5f5d43df-3764-4e3f-af10-b35d8c81d9ce",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "05e13967-9c0a-46df-a12d-fc7df594512f",
                "ordinal": 3
              }
            ],
            "lineageTag": "2323099a-2c8e-45d4-8594-a03a77e81203"
          }
        ],
        "isHidden": true,
        "lineageTag": "ebb3da40-fa26-4e26-9470-ecbf765f5311",
        "partitions": [
          {
            "name": "LocalDateTable_d35d2461-f30e-4251-8eae-e26f037d9476",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('YourOrg issues'[updated])), 1, 1), Date(Year(MAX('YourOrg issues'[updated])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_6ea7635f-d568-4e29-b629-3306888ad0be",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5457f90f-b345-423b-abea-012dc04c4063",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "97a220c8-8098-4abe-a5db-e031d17c0fe0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "de687bdb-5187-47e2-9d38-a1da01ede7e8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cfa14eef-7997-4b4b-9c97-6f71f6d399f2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "50a4b7ad-bea3-400b-9f02-33887ef3db32",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b446fe38-1c13-4726-9a82-8e476235df57",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "eeb1c3be-3e11-4d63-840d-0b3ca9485d7e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1bf24554-4681-462a-836e-d463d7b92b44",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "7a464fe3-1675-42ee-89a0-1302d69e3e42",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "a470c535-999f-4f7f-8a81-1525df523945",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "6cdf6e25-fd8a-4a9e-b5b1-869344527751",
                "ordinal": 3
              }
            ],
            "lineageTag": "3ec273e5-ce7a-4fef-bfc3-c2290c4761a5"
          }
        ],
        "isHidden": true,
        "lineageTag": "20177324-255a-421a-89f5-49260f1b3639",
        "partitions": [
          {
            "name": "LocalDateTable_6ea7635f-d568-4e29-b629-3306888ad0be",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('YourOrg issues'[lastViewed])), 1, 1), Date(Year(MAX('YourOrg issues'[lastViewed])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_988b7735-89b6-422d-aa32-ce3c2747d889",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8eeeebad-e846-42ef-9f47-e0285abdac67",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e89f7c43-f999-4f3f-908f-b00f8a5c723c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "29aad852-fa75-49f6-ab9b-a7972405e7b7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "01ccea1a-6db2-498e-a492-ad956fefa609",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "74efdd27-c99d-46dc-af17-5410e2fd2a68",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "649a1532-b2ec-40ad-824c-8e065994dcd9",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a2b46f43-2422-423b-a0de-1078db47e04f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "847b09bf-e6b5-4fb8-970d-964aa2701f9c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "ff8f56e7-5fee-4c48-8083-440d0919c66e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "13e60947-7f07-4430-9a06-930e7f07b409",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e7c1fd97-82db-4633-b4ca-3411b9f425d5",
                "ordinal": 3
              }
            ],
            "lineageTag": "0e6afd84-2004-4ba0-b9a3-8d5c3333640c"
          }
        ],
        "isHidden": true,
        "lineageTag": "79daacdf-5fec-4c17-96db-70e90e7a2ae8",
        "partitions": [
          {
            "name": "LocalDateTable_988b7735-89b6-422d-aa32-ce3c2747d889",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('YourOrg issues'[duedate])), 1, 1), Date(Year(MAX('YourOrg issues'[duedate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Status Codes",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Family",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "d9f1f8c4-46a8-4885-b947-2f3802d22ba7",
            "sortByColumn": "Status Rank",
            "sourceColumn": "Family",
            "summarizeBy": "none"
          },
          {
            "name": "Status Rank",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7c521ef3-e96c-4e0b-9e60-6393c332f78a",
            "sourceColumn": "Status Rank",
            "summarizeBy": "none"
          },
          {
            "name": "description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5cb0977-f86d-4a14-a55f-4042c2fe9b19",
            "sourceColumn": "description",
            "summarizeBy": "none"
          },
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "190dad8f-5e4e-4023-809c-a06bc9462312",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a54cb6e-10ae-44fa-ac80-d514deafe39d",
            "sortByColumn": "Status Rank",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "Is terminal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "68730141-b389-49ff-9286-b3cbedfbaf7b",
            "sourceColumn": "Is terminal",
            "summarizeBy": "none"
          }
        ],
        "description": "All the statuses in JIRA",
        "lineageTag": "4d93aed3-0bb0-4100-aace-a437ba1ed31f",
        "partitions": [
          {
            "name": "Status Codes",
            "mode": "import",
            "queryGroup": "03 Supporting Tables\\03.1 Staging\\03.2 Lookup tables",
            "source": {
              "expression": [
                "let",
                "    Source = #\"JIRA Lookup tables\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"status\"}),",
                "    #\"Expanded status\" = Table.ExpandRecordColumn(#\"Removed Other Columns\", \"status\", {\"description\", \"id\", \"name\"}, {\"description\", \"id\", \"name\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Expanded status\"),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Removed Duplicates\", {\"name\"}, #\"Status Ranks\", {\"status.name\"}, \"Status Ranks\", JoinKind.LeftOuter),",
                "    #\"Expanded Status Ranks\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Status Ranks\", {\"Family\", \"Is terminal\", \"Status Rank\"}, {\"Family\", \"Is terminal\", \"Status Rank\"}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Expanded Status Ranks\",{{\"id\", Order.Ascending}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Sorted Rows\",{{\"name\", \"Status\"}}),",
                "    #\"Changed types\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"id\", type text}, {\"Is terminal\", type logical}})",
                "in",
                "    #\"Changed types\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Environments Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "environment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0dde667-42c2-4ff4-bb34-26c3ce2ec44a",
            "sortByColumn": "Sort Order",
            "sourceColumn": "environment",
            "summarizeBy": "none"
          },
          {
            "name": "Env Cleaned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6ad891d-b7a8-4afb-869d-25319a8e4104",
            "sourceColumn": "Env Cleaned",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15ea3bde-1b2b-45d3-92af-7dff84ff4da8",
            "sourceColumn": "Sort Order",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8e1336ec-5282-4676-a053-971ab75fb8ea",
        "partitions": [
          {
            "name": "Environments Lookup",
            "mode": "import",
            "queryGroup": "03 Supporting Tables\\03.1 Staging\\0.3.1.1 Manual mappings",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"dY9BSwNBDIX/SpiThdldqp4EkYUV8WSxVZBtkbCTdhbHzTqTsfTfm67Vk15eQvK+l5m2NYvHh8bYn3JhNrY1ze2zhad6ZWG5urOAg4PTvg5B9XJyLSK73EnPwx88wJmjzyIQxqEfduX7wRMG8VuOod9SyXFXYp4pombV+QRmFO31sur59yQpDR07Ai8ypquqUlPhu38Sq5s9x7cxYEevR+q6Wdb39QuI7xMkzzk4wCxcjDzmgEK6IVibvUcBtRw4RzhGwJQxXV4b+MiUTj/9fd3mCw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [environment = _t, #\"Env Cleaned\" = _t, #\"Sort Order\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"environment\", type text}, {\"Env Cleaned\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"null\",null,Replacer.ReplaceValue,{\"environment\", \"Env Cleaned\"}),",
                "    #\"Uppercased Text\" = Table.TransformColumns(#\"Replaced Value\",{{\"environment\", Text.Upper, type text}})",
                "in",
                "    #\"Uppercased Text\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateDimension",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TheDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy/mm/dd",
            "isKey": true,
            "lineageTag": "a23b342f-689a-452c-938b-31c22af1b8d8",
            "sourceColumn": "TheDate",
            "summarizeBy": "none"
          },
          {
            "name": "TheUnixDateZeroHours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1ed1dba9-01dd-4500-b6a0-09a2a68de164",
            "sourceColumn": "TheUnixDateZeroHours",
            "summarizeBy": "none"
          },
          {
            "name": "TheDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5c9ff54a-034f-4869-8f2d-e9bccd9427d7",
            "sourceColumn": "TheDay",
            "summarizeBy": "none"
          },
          {
            "name": "TheDayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46abc28a-c0fa-49cb-a425-4abcf8df468f",
            "sourceColumn": "TheDayName",
            "summarizeBy": "none"
          },
          {
            "name": "TheWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b2ec2bc3-f9b5-42e3-ab79-74b31befd6f3",
            "sourceColumn": "TheWeek",
            "summarizeBy": "none"
          },
          {
            "name": "TheISOWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8154e90d-a22e-41d8-93bd-4853f3c15120",
            "sourceColumn": "TheISOWeek",
            "summarizeBy": "none"
          },
          {
            "name": "TheDayOfWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5d986d64-c181-42b3-b256-a4c252423656",
            "sourceColumn": "TheDayOfWeek",
            "summarizeBy": "none"
          },
          {
            "name": "TheMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "01d3ec2d-314d-44f1-ae9c-c4d4b0e7f56d",
            "sourceColumn": "TheMonth",
            "summarizeBy": "none"
          },
          {
            "name": "TheMonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f7a22ec-d388-457e-9f2c-139be184c218",
            "sourceColumn": "TheMonthName",
            "summarizeBy": "none"
          },
          {
            "name": "TheQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0df0f37c-47ca-47c6-b3f6-11f5c2d54b9b",
            "sourceColumn": "TheQuarter",
            "summarizeBy": "none"
          },
          {
            "name": "TheYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "28333fea-ad86-4621-b49a-a91376548a6e",
            "sourceColumn": "TheYear",
            "summarizeBy": "none"
          },
          {
            "name": "TheFirstOfMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy/mm/dd",
            "lineageTag": "ef487dc1-4b47-4dc9-aede-0f0a1d7dd60a",
            "sourceColumn": "TheFirstOfMonth",
            "summarizeBy": "none"
          },
          {
            "name": "TheLastOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy/mm/dd",
            "lineageTag": "c23b59b1-70ae-4c61-9250-73a2ee917145",
            "sourceColumn": "TheLastOfYear",
            "summarizeBy": "none"
          },
          {
            "name": "TheDayOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9d93768f-b901-4769-a5c5-b8bea4a4f7a8",
            "sourceColumn": "TheDayOfYear",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "47b9e66b-7026-4e3f-8bbf-27bb11fd5c56",
        "partitions": [
          {
            "name": "DateDimension",
            "mode": "import",
            "queryGroup": "01 Utilities",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Server, Database),",
                "    dbo_DateDimension = Source{[Schema=\"dbo\",Item=\"DateDimension\"]}[Data]",
                "in",
                "    dbo_DateDimension"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_bf00ef03-f29e-4420-b353-30eeec4d0eaa",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b0bbc5ff-5dae-4b53-b832-2041eb6b7424",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5b6f26b0-3899-4600-ba8c-a07e3c4f56fc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e0387afb-95df-41fc-96a2-14e760355f33",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d79231be-2919-4501-99b1-88d8fe32dd7e",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9df6e778-ee0b-4925-ae18-78f25cb8e64c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e90e2903-bfd1-4d54-827b-d840f70b47dc",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ba21c0c8-a602-4a6c-85f2-216aba54bde7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1c5c6587-f440-48b5-af10-58da3c06a87a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "4f4331b3-712e-467c-a031-e24248c013dc",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5730c758-4f25-4c79-99f3-b8d908023f93",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ef58ee34-6b6f-436c-9a75-9c70b99e290d",
                "ordinal": 3
              }
            ],
            "lineageTag": "21056075-d9a4-4c07-8604-20aa8e8b14bc"
          }
        ],
        "isHidden": true,
        "lineageTag": "fd9574fa-411f-4253-8c33-273d3485d486",
        "partitions": [
          {
            "name": "LocalDateTable_bf00ef03-f29e-4420-b353-30eeec4d0eaa",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('YourOrg issues'[created])), 1, 1), Date(Year(MAX('YourOrg issues'[created])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Report last refresh",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Report last refreshed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "4436e61c-452f-43bf-bfce-8181544214e2",
            "sourceColumn": "Report last refreshed",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_3860530a-946d-4dbd-a261-9cddf2ac696b"
                },
                "isDefault": true,
                "relationship": "2519a7b8-8244-43fe-8a6b-51318cd20abd"
              }
            ]
          }
        ],
        "lineageTag": "bf9b8781-8e93-477f-a782-9485f598984b",
        "partitions": [
          {
            "name": "Report last refresh",
            "mode": "import",
            "queryGroup": "01 Utilities",
            "source": {
              "expression": [
                "let",
                "    Source = DateTime.LocalNow(),",
                "    #\"Converted to Table\" = #table(1, {{Source}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Converted to Table\",{{\"Column1\", type datetime}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Column1\", \"Report last refreshed\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_3860530a-946d-4dbd-a261-9cddf2ac696b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c2203aa0-ec2f-4db8-a753-8d1d74c28834",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4daddde0-7eea-44ff-9b7c-275b4260f9fb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bd168a17-13d1-4365-8d3c-a6167b08f87d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fd6256a7-30d1-4559-b45f-d6fee20f1da3",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1032fb62-5baf-48ae-9cbb-5cb5d27dc00d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a1f885f8-9c10-4818-b9a8-7588212b76be",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "635d450e-0395-4cb4-820c-e6e6cc0e9188",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "13ad8519-6505-449b-8b4c-e6a84f19193b",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6fa75404-32e8-446b-836e-3a5201effdf5",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b41a8778-4c74-43fd-b58d-874e4dae883a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "940583c8-7f6f-491e-918f-f91c15a6be9f",
                "ordinal": 3
              }
            ],
            "lineageTag": "cc7f8e2f-09df-4dea-b5ec-0fb28e721407"
          }
        ],
        "isHidden": true,
        "lineageTag": "6ea00dab-e2ba-407b-81d0-17e240058bb2",
        "partitions": [
          {
            "name": "LocalDateTable_3860530a-946d-4dbd-a261-9cddf2ac696b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Report last refresh'[Report last refreshed])), 1, 1), Date(Year(MAX('Report last refresh'[Report last refreshed])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "MeasuresTable",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "fd0df1c5-53ce-4997-9be9-4f6abbd43477",
        "measures": [
          {
            "name": "Blocked Tickets",
            "expression": [
              "CALCULATE(",
              "    [Tickets]",
              "    , 'Status Codes'[Family] = \"Blocked\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "bb3b243f-5fb3-465d-844a-a721767f55c1"
          },
          {
            "name": "Cancelled Tickets",
            "expression": [
              "CALCULATE(",
              "    [Tickets]",
              "    , 'Status Codes'[Family] = \"Cancelled\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "3c0c9e24-6c1a-47d2-b7df-b2b4a9a0cb4a"
          },
          {
            "name": "Waiting Tickets",
            "expression": [
              "CALCULATE(",
              "    [Tickets]",
              "    , (",
              "        'Status Codes'[Family] = \"Waiting\" ",
              "        || 'Status Codes'[Family] = \"Awaiting Business\"",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "d64f2918-cf4c-4553-b2ac-a7f15b16d911"
          },
          {
            "name": "Active Tickets",
            "expression": [
              "CALCULATE(",
              "    [Tickets]",
              "    , NOT(",
              "\t    'Status Codes'[Family] = \"Blocked\"",
              "\t    || 'Status Codes'[Family] = \"Cancelled\"",
              "\t    || 'Status Codes'[Family] = \"Done\" ",
              "\t    ||  'Status Codes'[Family] = \"Cloned\"",
              "\t    ||'Status Codes'[Family] = \"Waiting\" ",
              "        || 'Status Codes'[Family] = \"Awaiting Business\"",
              "    ) // end not - can't just subtrack the other statuses bc it goes wobbly when filtering by status",
              ") // end calculate"
            ],
            "formatString": "0",
            "lineageTag": "42830f16-d860-407d-be4a-33e7d0d1dacd"
          },
          {
            "name": "Resolved Tickets",
            "expression": [
              "CALCULATE(",
              "    [Tickets]",
              "    , 'Status Codes'[Family] = \"Done\" ||  'Status Codes'[Family] = \"Cloned\"",
              ") // end calc"
            ],
            "formatString": "0",
            "lineageTag": "1dad6b8e-4075-40bd-b8ea-bdb7b38de540"
          },
          {
            "name": "Tickets",
            "expression": [
              "CALCULATE(",
              "    DISTINCTCOUNT('YourOrg issues'[issue ID])",
              "    , USERELATIONSHIP('YourOrg issues'[created - Date], DateDimension[TheDate])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c5203401-2dfd-4c57-a618-3fd1a7f3b273"
          }
        ],
        "partitions": [
          {
            "name": "MeasuresTable",
            "mode": "import",
            "queryGroup": "01 Utilities",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Priorities",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "self",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "WebUrl",
            "dataType": "string",
            "lineageTag": "e58efa64-7aed-45ab-af30-1b1cd4188926",
            "sourceColumn": "self",
            "summarizeBy": "none"
          },
          {
            "name": "Priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "934aa2c7-d03e-4b6d-bdd3-d8d264dc5764",
            "sortByColumn": "id",
            "sourceColumn": "Priority",
            "summarizeBy": "none"
          },
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce8e9cd7-85df-499a-8507-dc31f1b1e580",
            "sourceColumn": "id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1e069bc1-10d3-4ecc-8d60-778ef46322f6",
        "partitions": [
          {
            "name": "Priorities",
            "mode": "import",
            "queryGroup": "03 Supporting Tables\\03.1 Staging\\03.2 Lookup tables",
            "source": {
              "expression": [
                "let",
                "    Source = #\"JIRA Lookup tables\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"priority\"}),",
                "    #\"Expanded priority\" = Table.ExpandRecordColumn(#\"Removed Other Columns\", \"priority\", {\"self\", \"name\", \"id\"}, {\"self\", \"name\", \"id\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Expanded priority\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Duplicates\",{{\"name\", \"Priority\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"id\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fixes",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "self",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "WebUrl",
            "dataType": "string",
            "lineageTag": "a0b05bcb-0e64-4dea-bc07-ada2da36a67c",
            "sourceColumn": "self",
            "summarizeBy": "none"
          },
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c38deffb-cc89-49c3-9b50-7296065b1677",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71d17bf2-4a40-4408-9ff6-66dd21d7b887",
            "sourceColumn": "description",
            "summarizeBy": "none"
          },
          {
            "name": "Fix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "78641c9c-3161-42e3-83a1-ba9a76d35c02",
            "sourceColumn": "Fix",
            "summarizeBy": "none"
          },
          {
            "name": "archived",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5cea3313-7e0d-4d3b-ae26-2e5260618b91",
            "sourceColumn": "archived",
            "summarizeBy": "none"
          },
          {
            "name": "released",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5cad35e7-1c6b-4dc8-9b0f-92bb05b43b7c",
            "sourceColumn": "released",
            "summarizeBy": "none"
          },
          {
            "name": "releaseDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy/mm/dd",
            "lineageTag": "bfca6da0-ce72-4881-a790-71d6d61e55f0",
            "sourceColumn": "releaseDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c2bb7f89-a9fe-4656-a0d6-e5399e5c4f08"
                },
                "isDefault": true,
                "relationship": "6da0cc40-abd2-4c06-84a2-809ce862fb2c"
              }
            ]
          }
        ],
        "lineageTag": "ea8878f1-77ef-4706-b487-d73627e64de3",
        "partitions": [
          {
            "name": "Fixes",
            "mode": "import",
            "queryGroup": "03 Supporting Tables\\03.1 Staging\\03.2 Lookup tables",
            "source": {
              "expression": [
                "let",
                "    Source = #\"JIRA Lookup tables\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"fixVersions\"}),",
                "    #\"Expanded fixVersions\" = Table.ExpandListColumn(#\"Removed Other Columns\", \"fixVersions\"),",
                "    #\"Expanded fixVersions1\" = Table.ExpandRecordColumn(#\"Expanded fixVersions\", \"fixVersions\", {\"self\", \"id\", \"description\", \"name\", \"archived\", \"released\", \"releaseDate\"}, {\"self\", \"id\", \"description\", \"name\", \"archived\", \"released\", \"releaseDate\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Expanded fixVersions1\"),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Removed Duplicates\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Blank Rows\",{{\"releaseDate\", type date}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"name\", \"Fix\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"id\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Devs",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "self",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "WebUrl",
            "dataType": "string",
            "lineageTag": "869cfc83-2278-4e03-85ea-41ae5e5141f7",
            "sourceColumn": "self",
            "summarizeBy": "none"
          },
          {
            "name": "accountId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "031918be-69ac-4f27-b07d-9a20e519c203",
            "sourceColumn": "accountId",
            "summarizeBy": "none"
          },
          {
            "name": "emailAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "941507bb-0e17-4d60-92c8-7eb99aac2046",
            "sourceColumn": "emailAddress",
            "summarizeBy": "none"
          },
          {
            "name": "avatarUrls.48x48",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "538c0a02-4dd4-4cfd-83bb-fd63878ffe8d",
            "sourceColumn": "avatarUrls.48x48",
            "summarizeBy": "none"
          },
          {
            "name": "avatarUrls.24x24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "ef420db2-0aa0-4ba0-ab76-9d0ad724f394",
            "sourceColumn": "avatarUrls.24x24",
            "summarizeBy": "none"
          },
          {
            "name": "avatarUrls.16x16",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "87e78b98-5eb6-4212-8981-67b88e332ebd",
            "sourceColumn": "avatarUrls.16x16",
            "summarizeBy": "none"
          },
          {
            "name": "avatarUrls.32x32",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "93ac0aa3-d287-405a-b2ca-e281ae2c713c",
            "sourceColumn": "avatarUrls.32x32",
            "summarizeBy": "none"
          },
          {
            "name": "displayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43d1d4d8-9acd-41e5-b0f8-61c242f6ebc8",
            "sourceColumn": "displayName",
            "summarizeBy": "none"
          },
          {
            "name": "active",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "f51484b1-dba9-40f7-b5bf-94b562801e53",
            "sourceColumn": "active",
            "summarizeBy": "none"
          },
          {
            "name": "timeZone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a195dc48-7cb7-404e-870c-ad8e907e9fff",
            "sourceColumn": "timeZone",
            "summarizeBy": "none"
          },
          {
            "name": "accountType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "91a6e296-162c-419d-83d3-a062ff96fa86",
            "sourceColumn": "accountType",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a942d02d-b409-471a-b5cd-c5c5d8a5ce67",
        "partitions": [
          {
            "name": "Devs",
            "mode": "import",
            "queryGroup": "03 Supporting Tables\\03.1 Staging\\03.2 Lookup tables",
            "source": {
              "expression": [
                "let",
                "    Source = #\"JIRA Lookup tables\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"assignee\"}),",
                "    #\"Expanded assignee\" = Table.ExpandRecordColumn(#\"Removed Other Columns\", \"assignee\", {\"self\", \"accountId\", \"emailAddress\", \"avatarUrls\", \"displayName\", \"active\", \"timeZone\", \"accountType\"}, {\"self\", \"accountId\", \"emailAddress\", \"avatarUrls\", \"displayName\", \"active\", \"timeZone\", \"accountType\"}),",
                "    #\"Expanded assignee.avatarUrls\" = Table.ExpandRecordColumn(#\"Expanded assignee\", \"avatarUrls\", {\"48x48\", \"24x24\", \"16x16\", \"32x32\"}, {\"avatarUrls.48x48\", \"avatarUrls.24x24\", \"avatarUrls.16x16\", \"avatarUrls.32x32\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Expanded assignee.avatarUrls\"),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Removed Duplicates\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Blank Rows\",{{\"active\", type logical}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Linked Issues",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Child key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a29917f-f4ac-4119-874c-d651005905c9",
            "sourceColumn": "Child key",
            "summarizeBy": "none"
          },
          {
            "name": "Parent key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00541337-d59d-4116-9cae-be1d64d96473",
            "sourceColumn": "Parent key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f47a492b-6658-47bf-b4b9-41d95de0075a",
        "partitions": [
          {
            "name": "Linked Issues",
            "mode": "import",
            "queryGroup": "04 Finalised Tables",
            "source": {
              "expression": [
                "let",
                "    Source = #\"YourOrg issues\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"issue key\", \"parent.key\"}),",
                "    #\"removed rows with no parents\" = Table.SelectRows(#\"Removed Other Columns\", each ([parent.key] <> null)),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"removed rows with no parents\",{{\"issue key\", \"Child key\"}, {\"parent.key\", \"Parent key\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c2bb7f89-a9fe-4656-a0d6-e5399e5c4f08",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ce8ddf85-1b10-4131-bd15-d0da86d8de9b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8f79af74-4330-4399-8616-80342cd5fe9c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c2359a0b-6bc7-4dde-829e-31addd233b5d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "384070cd-93ba-42e4-bbc1-c5fe6b6b2641",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3d3e60d3-d367-4804-aa07-e172e2f48cfa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4d13c7db-826f-4132-9511-5552cb3f16b2",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bb48051a-42a9-4123-9eeb-6805839d9e83",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7f2a3628-8c20-4276-96d3-1432dc48bb4a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e72f742a-923f-456e-9cf0-45610ae75073",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "7964a5f8-125e-4489-9a33-7cf178553cbf",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "cfbc6557-920f-4cf9-ac3d-a5fbac4ebf73",
                "ordinal": 3
              }
            ],
            "lineageTag": "002c2e93-42b3-46f2-8ec0-f3ed7a253743"
          }
        ],
        "isHidden": true,
        "lineageTag": "89693196-57b2-43a8-bf6f-1022fd2cd37c",
        "partitions": [
          {
            "name": "LocalDateTable_c2bb7f89-a9fe-4656-a0d6-e5399e5c4f08",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Fixes'[releaseDate])), 1, 1), Date(Year(MAX('Fixes'[releaseDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Projects",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "self",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "WebUrl",
            "dataType": "string",
            "lineageTag": "642774ac-2035-4624-b076-54df223db572",
            "sourceColumn": "self",
            "summarizeBy": "none"
          },
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a86b9cf2-6dbc-44ca-a3cc-84e53cc241ee",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea0eefd1-26da-4f39-9010-8454ba6040ef",
            "sourceColumn": "key",
            "summarizeBy": "none"
          },
          {
            "name": "Project",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "117dd649-6ad9-4ee9-82c5-0e5217da2c31",
            "sourceColumn": "Project",
            "summarizeBy": "none"
          },
          {
            "name": "projectTypeKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ffeeb2b3-293b-47ba-b8b6-8e1b525f5828",
            "sourceColumn": "projectTypeKey",
            "summarizeBy": "none"
          },
          {
            "name": "simplified",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84013e2b-9dec-44ee-9c57-1262a9cbadd1",
            "sourceColumn": "simplified",
            "summarizeBy": "none"
          },
          {
            "name": "avatarUrls.48x48",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "9d44f819-281e-4d84-ae23-d537fef3ecba",
            "sourceColumn": "avatarUrls.48x48",
            "summarizeBy": "none"
          },
          {
            "name": "avatarUrls.24x24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "29261b7d-32a3-4ac5-a828-5fa7b1edca70",
            "sourceColumn": "avatarUrls.24x24",
            "summarizeBy": "none"
          },
          {
            "name": "avatarUrls.16x16",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "f8d2c17d-0e59-4290-a411-e6534876a5cb",
            "sourceColumn": "avatarUrls.16x16",
            "summarizeBy": "none"
          },
          {
            "name": "avatarUrls.32x32",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "a8dc409a-b158-4269-ab85-8d3b9dea6247",
            "sourceColumn": "avatarUrls.32x32",
            "summarizeBy": "none"
          },
          {
            "name": "projectCategory.self",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "WebUrl",
            "dataType": "string",
            "lineageTag": "2f782610-b656-4269-9929-479664410c3d",
            "sourceColumn": "projectCategory.self",
            "summarizeBy": "none"
          },
          {
            "name": "projectCategory.id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a6f4ee1-a7dc-4f03-b1ac-d57bac9589c9",
            "sourceColumn": "projectCategory.id",
            "summarizeBy": "none"
          },
          {
            "name": "projectCategory.description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7fbb6841-2ea5-46ee-b6fa-22804cfe90c2",
            "sourceColumn": "projectCategory.description",
            "summarizeBy": "none"
          },
          {
            "name": "projectCategory.name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0fd65fcf-6b85-463d-9bcd-fa75e57c635e",
            "sourceColumn": "projectCategory.name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "eda4aec9-5929-40c5-9a98-e5c3cff37b6b",
        "partitions": [
          {
            "name": "Projects",
            "mode": "import",
            "queryGroup": "03 Supporting Tables\\03.1 Staging\\03.2 Lookup tables",
            "source": {
              "expression": [
                "let",
                "    Source = #\"JIRA Lookup tables\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"project\"}),",
                "    #\"Expanded project\" = Table.ExpandRecordColumn(#\"Removed Other Columns\", \"project\", {\"self\", \"id\", \"key\", \"name\", \"projectTypeKey\", \"simplified\", \"avatarUrls\", \"projectCategory\"}, {\"self\", \"id\", \"key\", \"project\", \"projectTypeKey\", \"simplified\", \"avatarUrls\", \"projectCategory\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Expanded project\"),",
                "    #\"Expanded avatarUrls\" = Table.ExpandRecordColumn(#\"Removed Duplicates\", \"avatarUrls\", {\"48x48\", \"24x24\", \"16x16\", \"32x32\"}, {\"avatarUrls.48x48\", \"avatarUrls.24x24\", \"avatarUrls.16x16\", \"avatarUrls.32x32\"}),",
                "    #\"Expanded projectCategory\" = Table.ExpandRecordColumn(#\"Expanded avatarUrls\", \"projectCategory\", {\"self\", \"id\", \"description\", \"name\"}, {\"projectCategory.self\", \"projectCategory.id\", \"projectCategory.description\", \"projectCategory.name\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded projectCategory\",{{\"project\", \"Project\"}}),",
                "    // Filtered out Service Mangement board, because all the other boards contain subtickets cloned off SM tickets. Also, completing items in sub-boards doesn't feedback to SM, so they stay open",
                "    // ",
                "    // Filtered out a board, as it's not relevant to this org group",
                "    #\"Filtered out non-group boards\" = Table.SelectRows(#\"Renamed Columns\", each ([Project] <> \"DQLD-Operations-Reporting\" and [Project] <> \"Service Management\"))",
                "in",
                "    #\"Filtered out non-group boards\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_7ae11d14-c76b-45f3-8f69-4a03985e8149",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e5fd7b3b-dc59-4a4e-9e1f-178ea3069af6",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8886a305-4955-4503-a0ba-46a76bba7e6d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "64c97f89-03ac-4431-bee4-db4a6409f994",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3c4c32c7-05f8-4deb-8762-f98615635e08",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2080abef-d04e-48f2-a691-eb3a0e2217ef",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "21d28e27-d732-420b-9c0c-7bb3fc7e4135",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6a0cda15-4a10-4d96-96d2-f5d763b81e51",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1858fbb9-86c5-4a72-bb3f-740b2d094736",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "4c463cac-4d15-49da-ad21-7ea125ccfcc1",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3ba11497-9ec4-425d-820a-38e7d3ce728e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "dfe3c9ec-22a3-4a5f-a332-5ca5ac137487",
                "ordinal": 3
              }
            ],
            "lineageTag": "1631b25c-52e3-4616-95ac-714854c9f433"
          }
        ],
        "isHidden": true,
        "lineageTag": "b0c78c2e-97ce-4ae3-b629-562e0c82a3d6",
        "partitions": [
          {
            "name": "LocalDateTable_7ae11d14-c76b-45f3-8f69-4a03985e8149",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('YourOrg issues'[Resolution Date Improved])), 1, 1), Date(Year(MAX('YourOrg issues'[Resolution Date Improved])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Issue Types",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "self",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1ad0b14-a386-4647-ba28-9dc93e0df967",
            "sourceColumn": "self",
            "summarizeBy": "none"
          },
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94bfee61-ae1b-4526-ad97-30b1ef306d6c",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "iconUrl",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5288ee03-3b9c-46d5-b77e-8e215c123fc6",
            "sourceColumn": "iconUrl",
            "summarizeBy": "none"
          },
          {
            "name": "Issue Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c77fe2f1-3fb9-4e60-9a39-c95ec89d8a64",
            "sourceColumn": "Issue Type",
            "summarizeBy": "none"
          },
          {
            "name": "is subtask",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "b2f965a7-86d0-4095-8914-67cdbaa41211",
            "sourceColumn": "is subtask",
            "summarizeBy": "none"
          },
          {
            "name": "avatarId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea624b11-5990-4242-a159-cca7b1cce45d",
            "sourceColumn": "avatarId",
            "summarizeBy": "none"
          },
          {
            "name": "hierarchyLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ab2792c6-89ac-49e4-ab20-ef0cfadedb58",
            "sourceColumn": "hierarchyLevel",
            "summarizeBy": "none"
          },
          {
            "name": "Issue type description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2890d10-57db-4e1b-99e4-1d54647e41bd",
            "sourceColumn": "Issue type description",
            "summarizeBy": "none"
          },
          {
            "name": "Issue type family",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3bd42cd7-966f-4e9a-93b9-50c995ca2c75",
            "sourceColumn": "Issue type family",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c92ff046-27c6-44c0-ac99-56ce866f6282",
        "partitions": [
          {
            "name": "Issue Types",
            "mode": "import",
            "queryGroup": "03 Supporting Tables\\03.1 Staging\\03.2 Lookup tables",
            "source": {
              "expression": [
                "let",
                "    Source = #\"JIRA Lookup tables\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"issuetype\"}),",
                "    #\"Expanded issuetype\" = Table.ExpandRecordColumn(#\"Removed Other Columns\", \"issuetype\", {\"self\", \"id\", \"description\", \"iconUrl\", \"name\", \"subtask\", \"avatarId\", \"hierarchyLevel\"}, {\"self\", \"id\", \"description\", \"iconUrl\", \"name\", \"is subtask\", \"avatarId\", \"hierarchyLevel\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded issuetype\",{{\"is subtask\", type logical}, {\"hierarchyLevel\", Int64.Type}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type\", {\"name\"}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Removed Duplicates\", {\"name\"}, #\"Issue Families\", {\"Issue type\"}, \"Issue Families\", JoinKind.LeftOuter),",
                "    #\"Expanded Issue Families\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Issue Families\", {\"Issue type description\", \"Issue type family\"}, {\"Issue type description\", \"Issue type family\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded Issue Families\",{\"description\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"name\", \"Issue Type\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}